language: clojure
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.lein"
  - "$HOME/.m2"
services:
  - redis-server
env:
  global:
    - REDIS_URL="redis://localhost:6379" REDIS_TIMEOUT="4000"
script:
- lein cljfmt check
- lein eastwood
- lein test
after_success:
- CLOVERAGE_VERSION=1.0.7-SNAPSHOT lein cloverage --codecov
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
notifications:
  email: false
  slack:
    secure: tsgD6DpIWz1fyUy2BtwSS9fDtn5CHCTQ8hckXnILe/Pgx0Y2sk9cLlJhDMObnTK8wL9NEOvx1MpJw9vK//FmG8JriwdOjl1jjj644U488jKsCF3rnAWvxKA5i7cCGPob2di8u/zvUYwctGIQSeyAb68V8geNO9/UA9Wpb1wRGJJMLMbn6MmUmHuhkV+9VizMJ/x3aTyAMxbCfkAxE68fQjLcqAfPr7Jp55s3vosLqnsAfBPN1hNHKXeIDhRNnHfzJN+0ZJb7dUQL3GqOARG5vrWH3xtgn285of+rZtJvz3s6Apu93SXK2vfdRpOZ/GN8B0DGUaK5SKA1EUHVUbZpGDeCj1LFpGiTH7+BD7O47/ANhwjyVWI9f8zqElDzUlh4RMeJu7vhmp7e+YfmQx8arulapFGpoiclQ888G4E9pib8METUfDLWOeyRKQzGHH2ZksrPY+IEPLhzq6rMAAEtn38v68jZIKjbOy0QMx61W8WB4PI9Lc2PFPfzpu1W+tMTeyAUJnKNTZ1ay75vDmJ2osBx38/VDchs2et0qkiN/yyQ6GYPOFlmd9GfZjN94abRw7R7jQZ3pskoOufj/GZtClFv2bHbfK8Cuzg4a5V0ZxueELZiXNFAZntgDuUo9vTfRbcfVRxnZr4NwfYpkD8aa+prt+TM1wgd3nFmtMtYh6o=
