language: clojure
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.lein"
  - "$HOME/.m2"
services:
- redis-server
env:
  global:
  - REDIS_URL="redis://localhost:6379" REDIS_TIMEOUT="4000"
script:
- lein cljfmt check
- lein eastwood
- lein test
after_success:
- CLOVERAGE_VERSION=1.0.7-SNAPSHOT lein cloverage --codecov
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
notifications:
  email: false
  slack:
    secure: hhmqY9BrfJnzG381gQURd7NdyVWIi8CWYo8z7jeUPSWcAAGkC9vbgqss7Ziz9QB0zeVTua0tYnj/mmf/ndbzhNJ0NOIizArX1OVgJ1US7IpedeO7WogAIV//UfxGfmlfr2wrYQCy+039V1CkrVE5VXVkdEQEVHGfCRqCUrjoDlgTtUuDb2nJineN5raEOE/6y8x5Z//3OEcARnqFFw2MnO0HwGy7PmB3xB4r7DSUEDDx34kUA8FrnQG8h7zWwjCxF8ca9uQSiwPKfBFbMgyIdkVy5XYqy/NZknh62G0sgBoIVh0+KdCeps6NXjZczrScJSW/00vO5DpYstPPLIZDE8KZbH3Q9P+t69BTiQ2BD/tLxx57dum7eHA9UuOaw2X1vHmvP9Cs4O8FyYxWCoC5lBfxC9I8A32JoV4i+KKljCXmeqNVpaqjVBjlz6IeYBADqMvmXrb0HcWlIbEvEwNDD7CvV/dbtdlu2YyQLI1epNRVmdeiirZWhKREWmAmM6Ge+k/m95z6jx9usjVY0jnE+ZJQjwFvG5REErTlR9PVWawlUcTp+ai7sSON7qkGwHw1MgqYh8el+gNBVjo/ReDieKWD45mk8sNBnR6uMyZoa9EXZZyFkaOy+HvEuNDYR8vWK5gEMrIVJf3+ulqSeQTJZ6JxHaIAPYBMvaQx1mv+TvY=
